# Generated by Django 6.0.6 on 2026-07-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField(unique=True)),
                ('owner', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=280)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_url', models.URLField(max_length=500)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('license_name', models.CharField(blank=True, max_length=200, null=True)),
                ('default_branch', models.CharField(blank=True, max_length=200, null=True)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('watchers', models.PositiveIntegerField(default=0)),
                ('open_issues', models.PositiveIntegerField(default=0)),
                ('github_created_at', models.DateTimeField()),
                ('github_updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'repositories',
                'indexes': [models.Index(fields=['owner'], name='repositorie_owner_9ddf69_idx'), models.Index(fields=['name'], name='repositorie_name_174419_idx'), models.Index(fields=['language'], name='repositorie_languag_9b73bf_idx')],
            },
        ),
    ]
