# Generated by Django 6.0.6 on 2026-07-08 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=100)),
                ('popularity_score', models.PositiveSmallIntegerField(default=0)),
                ('activity_score', models.PositiveSmallIntegerField(default=0)),
                ('documentation_score', models.PositiveSmallIntegerField(default=0)),
                ('maintainability_score', models.PositiveSmallIntegerField(default=0)),
                ('overall_score', models.PositiveSmallIntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='api.repository')),
            ],
            options={
                'db_table': 'analysis',
            },
        ),
    ]
