# Generated by Django 6.0.6 on 2026-07-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='topics',
            field=models.JSONField(default=list),
        ),
    ]
