# Generated by Django 6.0.6 on 2026-07-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_repository_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='recommendations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
