# Generated by Django 6.0.6 on 2026-07-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_analysis_ai_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='code_quality_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
