# Generated by Django 6.0.6 on 2026-07-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_analysis_code_quality_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='community_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
