# Generated by Django 6.0.6 on 2026-08-12 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_analysis_community_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='api.repository'),
        ),
        migrations.AlterModelTable(
            name='analysis',
            table=None,
        ),
    ]
